"""add soft delete in issue

Revision ID: 3126c4232891
Revises: f96c98963120
Create Date: 2026-04-29 16:04:44.959495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3126c4232891'
down_revision: Union[str, Sequence[str], None] = 'f96c98963120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'is_deleted')
    # ### end Alembic commands ###
