"""set unique constraint

Revision ID: f96c98963120
Revises: 607d2a9e3fea
Create Date: 2026-04-29 11:26:21.366276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96c98963120'
down_revision: Union[str, Sequence[str], None] = '607d2a9e3fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_project', 'project_members', ['user_id', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_project', 'project_members', type_='unique')
    # ### end Alembic commands ###
